### ISSUE TITLE
Feature Request: Add supysonic-daemon support

### ISSUE THREAD

**Issue by DeadEnded** [ogarcia/docker-supysonic#1]
I have been playing with supysonic containers and haven't found one that enables the daemon.
I think this has to be rolled into the `entrypoint.sh`.

Is this something that could be added?
I tried starting the `supysonic-daemon` in the container and got a permissions denied error:
```
/ $ /usr/local/bin/python3 -m supysonic.daemon
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/supysonic-0.6.3-py3.9.egg/supysonic/daemon/__main__.py", line 11, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/supysonic-0.6.3-py3.9.egg/supysonic/daemon/__init__.py", line 63, in main
    daemon.run()
  File "/usr/local/lib/python3.9/site-packages/supysonic-0.6.3-py3.9.egg/supysonic/daemon/server.py", line 51, in run
    self.__listener = Listener(
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 453, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 596, in __init__
    self._socket.bind(address)
PermissionError: [Errno 13] Permission denied
```

There are instructions to set it up as a `systemd service` but since containers typically don't run systemd, my assumption is that you can instead wrap this up in the `entrypoint.sh` to get it working.

Thanks!
DeadEnd

**Comment by DeadEnded** [comment]
Okay - I figured out the permission issue (root).
Now I see the real error when I try to start the daemon from within the container:
```
/ # /usr/local/bin/python3 -m supysonic.daemon
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/orm/dbapiprovider.py", line 55, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/orm/dbapiprovider.py", line 230, in connect
    return provider.pool.connect()
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/orm/dbapiprovider.py", line 351, in connect
    pool._connect()
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/orm/dbproviders/sqlite.py", line 660, in _connect
    pool.con = con = sqlite.connect(filename, isolation_level=None, **pool.kwargs)
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/supysonic-0.6.3-py3.9.egg/supysonic/daemon/__main__.py", line 11, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/supysonic-0.6.3-py3.9.egg/supysonic/daemon/__init__.py", line 61, in main
    init_database(config.BASE["database_uri"])
  File "/usr/local/lib/python3.9/site-packages/supysonic-0.6.3-py3.9.egg/supysonic/db.py", line 660, in init_database
    metadb.bind(**settings)
  File "<string>", line 2, in bind
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/utils/utils.py", line 78, in cut_traceback
    reraise(exc_type, exc, full_tb)
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/utils/utils.py", line 61, in cut_traceback
    try: return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/orm/core.py", line 774, in bind
    self._bind(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/orm/core.py", line 796, in _bind
    self.provider = provider_cls(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/orm/dbproviders/sqlite.py", line 344, in __init__
    DBAPIProvider.__init__(provider, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/orm/dbapiprovider.py", line 130, in __init__
    connection, is_new_connection = provider.connect()
  File "<string>", line 2, in connect
  File "/usr/local/lib/python3.9/site-packages/pony-0.7.14-py3.9.egg/pony/orm/dbapiprovider.py", line 72, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: unable to open database file

```

**Comment by DeadEnded** [comment]
so... it seems that to run the `supysonic-daemon` you have to run it as root... but then it tries to connect to the DB which root does not have access to... 

So... I'll scratch my head on this one for awhile next.... :-)

**Comment by ogarcia** [comment]
The problem is that the default configuration of daemon points to a directory without write permissions. You must add this line in your config file under `[daemon]` section:
```
socket = /var/lib/supysonic/supysonic-daemon.sock
```

For example, a full minimal config file:
```
[base]
database_uri = sqlite:////var/lib/supysonic/supysonic.db

[webapp]
cache_dir = /var/lib/supysonic/cache
log_file = /var/log/supysonic/supysonic.log
log_level = WARNING

[daemon]
log_file = /var/log/supysonic/supysonic-daemon.log
log_level = INFO
socket = /var/lib/supysonic/supysonic-daemon.sock
```

I'll update the docker image to support this via environment variable

**Comment by ogarcia** [comment]
Done!

Anyway I recommend you that use `scan` in a cron instead of daemon, this wastes less resources than running a process. First start supysonic server:
```
docker run -d \
  --name=supysonic \
  -v /srv/supysonic:/var/lib/supysonic \
  -v /srv/supysonic/log:/var/log/supysonic \
  -v /media:/media \
  ogarcia/supysonic
```

And then perform scan:
```
docker exec supysonic /usr/local/bin/supysonic-cli folder scan
```

**Comment by DeadEnded** [comment]
Fantastic!
Thank you very much!
I hadn't looked at default pathing etc.
I'm glad it wasn't a too complicated fix!

So, now I can enter the container as a regular user and execute `/usr/local/bin/python3 -m supysonic.daemon` and the daemon starts right up.  The next thing is to have it start with the container.  

I am making an attempt at this in a PR.
Unfortunately, my knowledge is lacking... I can run the command within the container no problem, but executing it from `entrypoint.sh` is constantly failing.

I have tried:
  ```supysonic-daemon```
  ```exec /var/lib/supysonic/daemon.sh``` (deamon script uses the below `nohup` commands - and the `daemon.sh` works on its own)
  ```exec /bin/sh -c "/var/lib/supysonic/daemon.sh"```
  ```nohup /usr/local/bin/python3 -m supysonic.daemon > /var/log/supysonic/supysonic-daemon.log 2>&1 &```
  ```nohup /bin/sh -c "/usr/local/bin/python3 -m supysonic.daemon" > /var/log/supysonic/supysonic-daemon.log 2>&1 &```
... and a few more variations I didn't document because they failed as well.

I'm scratching my head again... not sure how to call this from the `entrypoint.sh` - and not seeing anything useful in the logs as to why it's failing.  Once I figured this out, I was thinking to wrap it in an `if` statement, and add an environmental variable to the `dockerfile` so it's optional, and off by default.

Any knowledge you might be able to share as to how this should be done?

Thanks for the help!
DeadEnd

**Comment by ogarcia** [comment]
You can make a new function on `entrypoint.sh`:
```sh
function ssdaemon {
  sleep 6
  /usr/local/bin/python3 -m supysonic.daemon
}
```

Simply sleep some seconds (to give time to start supysonic server) and run daemon.

Then call `ssdaemon` before run server (with `&` at end to send to background):
```sh
# Exec CMD or supysonic by default if nothing present
if [ $# -gt 0 ];then
  exec "$@"
else
  case ${SUPYSONIC_RUN_MODE} in
    fcgi)
      ssdaemon &
      fcgi
      ;;
    standalone)
      ssdaemon &
      standalone
      ;;
    *)
      echo "Run mode not recognized, switching to standalone debug server mode"
      standalone
      ;;
  esac
fi
```

**Comment by ogarcia** [comment]
I added the change to docker image, if you run:
```
docker run -d \
  --name=supysonic \
  -e SUPYSONIC_DAEMON_ENABLED=true \
  -v /srv/supysonic:/var/lib/supysonic \
  -v /srv/supysonic/log:/var/log/supysonic \
  -v /media:/media \
  ogarcia/supysonic
```
You have the server running with the daemon

**Comment by DeadEnded** [comment]
Thank you!
I didn't think to have delayed the daemon to let the `supysonic-server` start first... shows how little I know of what is going on :-) .
I have wiped my previous config and started over to make sure this works without issue.
I did run into one issue... there is a permission issue if you let docker create the folder structure on the host.
I think (easily could be misunderstanding it) that the folders have to have `owner:group 100:100` to allow the files to be created etc.
Alternatively, you can probably `chmod` the permissions to allow access as well.

I tested by wiping everything out and then starting the container.
There are permission errors and the folders are created with the role that Docker is running under.
When I `chmod` the config and log folders on the host to `100:100` everything works fine.
After that, I see all files generated (db, config, cache, logs, etc.) with owner/group `100:100` as well.

I don't know if this is something that should be put into the docs so users know how to fix permission issues, or if there is a way to fix it in the docker file (to create the volumes using `100:100` instead of the user docker is running as).

Cheers and Thanks again!
DeadEnd

**Comment by ogarcia** [comment]
> I don't know if this is something that should be put into the docs so users know how to fix permission issues, or if there is a way to fix it in the docker file (to create the volumes using `100:100` instead of the user docker is running as).

This is simply _the docker way_, if you mount a volume that you want a user to use, you must give him the correct permissions. Anyway I have improved the README.

**Comment by DeadEnded** [comment]
Awesome job!
Thanks for all the work!
